### PR TITLE
Internalize more auth logic

### PR DESCRIPTION
**Pull request by balloob**
This adds more of the auth logic inside PyAlmond. Now for local instances no extra work is necessary. For OAuth2 instances it's only required to implement token refreshing.

### CODE REVIEW

**Review by gcampax — APPROVED** [review]
Looks good

**Comment by balloob** [comment]
Works 👍 
image

**Comment by gcampax** [comment]
Nice! I'll merge this, and then probably write some tests and maybe linting. By the way, do you want commit access to this repo? Given that Home Assistant is the only user of this library yet...

**Comment by balloob** [comment]
Yeah that's great.

**Pull request merged**
